# Utiliser une image de base Node.js plus légère
FROM node:20-alpine

# Définir le répertoire de travail dans le conteneur
WORKDIR /usr/src/app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances et nettoyer le cache npm
RUN npm install --production && npm cache clean --force

# Copier uniquement les fichiers nécessaires
COPY src/ src/

# Commande pour démarrer l'application
CMD ["node", "src/index.js"]
